### ISSUE TITLE
committee meetings scraper fixes and improvements

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#490]
this issue is an aggregation of multiple problem all relating to committee meeting scraper:

- [x] #444 protocols are not up to date
- [x] #448 delete the doctype header in protocols
- [x] #432 #450 protocol invitees section is confusing
- [x] #399 improve committee meeting scraper

**Comment by OriHoch** [comment]
meeting scraper was improved in [v2.8.0](https://github.com/hasadna/Open-Knesset/releases/tag/v2.8.0)

still some more work to do

**Comment by OriHoch** [comment]
deployed, but need to do more testing

**Comment by OriHoch** [comment]
everything looks ok, closing the issue :exclamation:
